### ISSUE TITLE
Computer crashes whenever I start mining.

### ISSUE THREAD

**Issue by CryptoHypnos** [nanopool/Claymore-Dual-Miner#103]
So whenever I start mining 
>the GPU fan starts spinning at a 100%
>the computer restarts
>black screen, fan still running at 100%

I've tried NiceHash and Claymore.

Here's my setup:
Gigabyte GA-78LMT-USB3
AMD FX(tm)-6300 Six-Core Processor
4 GB DDR3
450 W crummy PSU
RX 560 Saphphire Pulse

So the GPU does not have a power connector so my only conclusion is that the motherboard isn't providing enough power. However under a stress test using MSI Kombustor this problem does not occur.

I'm hoping the problem will vanish on my mining motherboard H81 PRO BTC R2.0 as it has two extra power connectors to the motherboard.
I won't be able to test that theory until I get the RAM module for the mining rig.

Until then, any thoughts?

UPDATE:
So I've tried switching cards and its twin seems to work, no problem.
I guess it was a faulty card...

**Comment by HornedSalmon** [comment]
So the issues section of git is for sure not the place to post this sort of thing. Especially when you reproduced the issue in different software as well.

**Comment by CryptoHypnos** [comment]
Apologies.
Should I take it off?
