### ISSUE TITLE
incorrect shares on second hand GPU

### ISSUE THREAD

**Issue by Roaders** [nanopool/Claymore-Dual-Miner#117]
Hi All

I got a used GTX 1070 card off ebay and have installed it in my mining rig. I am getting 26.6 MH/s out of it but over the last 14 hours it has produced 133 shares with 212 incorrect ones.

I get the message:

```
GPU #7 got incorrect share. If you see this warning often, make sure you did not overclock it too much.
```

so it seems likely that the previous owner overclocked it.
I had thought that overclocking would be a software setting so installing in a new PC would mean that the card would revert to factory settings.

Any advice on how to revert this? I am running on Linux (but have access to windows) so I imagine it's going to be a bit of a pain.

At least initially I just want to return to normal factory settings.

Thanks

**Comment by ADSC17** [comment]
@Roaders  I'm not sure which pool or brand of 1070 you have however a owner from previously user overclocking it shouldn't be an issue unless they have modified the BIOS. Separately this is how your card should been preforming if all is correctly configured. 

![oc](https://user-images.githubusercontent.com/31831340/31591294-236c24fe-b216-11e7-84c8-4315f542fc77.jpg)

Two suggestions

1. Change pool i.e ethermine or drawfpool etc and have your settings similar to this;

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

2. If your noticing tearing whilsting mining to use the intensity of it, you can reference this in readme!!!.txt, command is -ethi (scales from 1-8, however 3.9 personally for me has been the sweet spot).

I hope this helps

**Comment by Roaders** [comment]
It actually seems that this has now resolved itself. I reinstalled all my cards and re-ran the power cables.
Maybe before the card wasn't getting enough power or something.
