### ISSUE TITLE
Devfee operations reset Core Voltage settings

### ISSUE THREAD

**Issue by OnurVar** [nanopool/Claymore-Dual-Miner#154]
Hello,

when devfee operations start, they reset my Core Voltage settings to factory defaults. A new devfee operation starts (a new DAG is being created), then devfee stops. At this point my GPU Core Voltage is set to factory default. Even if I changed it using MSI AfterBurner, it's still going to factory.

 Any idea whats wrong ?

Batch : 
`EthDcrMiner64.exe -cvddc 950,950,950 -epool eu1-etc.ethermine.org:4444 -dcri 8 -ewal 0x0000000000000 -di 012 -epsw x -eworker rig-01 -wd 1 -esm 0 -mode 1`

**Comment by alfredopisano** [comment]
Im having the same issue, im not sure if i can pin point it to the DEVFEE process. but something keeps resetting my MSI AB settings. It seems that it resets my voltage, coreclock, memclock settings. I have amd rx580 cards with the mining amd driver, and i did NOT install the amd settings wattman app. I have tried with -nofee 1 and it also happened. Not sure if the miner is hitting an error and resetting everything? also im not specifiy anythin in my batch file regardding the -cvddc settings, that never seems to work for me.

**Comment by jwb6658** [comment]
Stop using afterburner and start using wattman for your amd cards. Amd can’t get their drivers straight and have tons of issues allowing third party to speak to their api’s. I stopped having issues the moment I started using wattman for everything.

**Comment by alfredopisano** [comment]
So i unistalled MSI Afterburner, DDU unistalled the driver, re-installed the AMD Mining Driver from August 2017 and set my settings in Wattman. I noticed i have to apply the new settings for each card after i start Claymore's miner. Then they have been sticking for the past 8 hours when i peep in through RDP. 

The only problem now is that when i shutdown Claymore's Miner 10.2 and re-start it they seem to be ignored even though the correct values show in Wattman settings for each card, each card is drawing more Wattage according to GPU-Z. When i re-apply the settings in Wattman, GPU-Z now shows the correct wattage draw.

Am i missing something? i tried specifying the voltage, core and mem Clock, Fan in the .bat file but they dont seem to do anything. I tried even specifying for each of my 5 cards comma deliminated values for each setting still they dont get applied.

Any other thoughts? i have the gigabyte arous rx580 4gb cards, windows 10 64bit 8gb ram, asrock h110 btc pro motherboard.

**Comment by alfredopisano** [comment]
spoke too soon, it got reset after 7.5hrs to default voltages, no restart command in claymore miner. I have been loging into the rig couple times a day to check its voltages through MS RDP, through an iphone and other PC, so im not sure if that has caused it. Some research about RDP sounds like it could be the cause of it. I will try real VNC and see if the problem goes away if i stop RDP into the rig... will keep posting things i try that dont work and if i ever find a solution, since i havent found anything else about this.

**Comment by OnurVar** [comment]
So basicly, I tried everything and this is what worked for me.

Im using MSI AfterBurner (not WattMan). I set my GPU settings on Claymore's Config file
`-cclock 1330,1330,1330,1330,1330,1330 -mclock 2145,2145,2145,2145,2145,2145`

so I'm closing this issue since this worked for me.
