### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by ItsDaWither** [nanopool/Claymore-Dual-Miner#158]
removed

**Comment by anon4425** [comment]
I too was confused by the different hash-rates given by the mining software and the mining stats page. 
I still may have it wrong.

But to answer your question i believe the miner's hash rate is the true hash-rate.
On my pool of choice(Dwarfpool.com) where it tells me my hash-rate it has two values hash-rate and reported hash-rate.
I haven't seen any sources for these php of js webpages so im not sure exactly how they get their numbers (most likely with the built in getstat1 command or a predetermined equation).

So i would go with the hash-rate on the miner.
As i get paid 99% close to the actual hash-rate on the miner where i would be making another $20 a week if i went with the pools report. 

As for your second question. It is not feasible to get much of a higher hash-rate with out overclocking. You may be able to get a MH/s or so but if your trying to get 5-10MH/s your going to need to change your timings(Bios mod) or overclock(undervolt and boost memory) 

If you have this card in a gaming rig I strongly discourage from bios modding as it likely will impede upon your frame rate.
Although if this is in a mining rig feel free to message me if you need help overclocking / bios modding.

**Comment by ishaan452** [comment]
Thanks. It's a gaming rig, want to use the earnings to support Twitch and better hardware and whatnot.

**Comment by ishaan452** [comment]
It tells me 15-17MH/s no matter what intensity I select, though. Very confusing. Also, 1 hour of mining got me 8 cents,not counting LBRY,  wouldn't that be representative of about 25MH/s or something similar?

**Comment by anon4425** [comment]
I would refer you to https://www.cryptocompare.com/mining/calculator/eth 
For your ETH calculations. but yes thats about how much you would make if you mined for an hour on 25MH/s unless the coin value went up
