### ISSUE TITLE
Startup scripts for Linux (shell + systemd)

### ISSUE THREAD

**Issue by evert-mouw** [nanopool/Claymore-Dual-Miner#161]
I'm using Linux and needed a startup script, so I wrote one. Have fun :)

https://github.com/evert-mouw/claymore-systemd-screen

**Comment by islamTaha12** [comment]
@evert-mouw I'm wondering how can u control your cards fan and temp in linux? I'm using windows just because of MSI afterburner

**Comment by jwb6658** [comment]
This is the only automation I have found.

https://github.com/Thodin3/custom-fanbytemp

**Comment by Andriuzz66** [comment]
Hello

Need help with Starting Claymore Dual on Linux Mint cinnamon. 
Can start it says cant recognize as internal or external command. 
my line:
ethdcrminer64 -epool eth-eu1.nanopool.org:9999 -ewal 0x1....... wallet address/workername/email.com -epsw x -mode 1 -dpool and second cryptocurrency address.

What do I do wrong?

Thanks

**Comment by evert-mouw** [comment]
@islamTaha12 Sorry you should just read the Claymore documentation and it's in the script as well. Also you might read up about VBIOS modding.
@Andriuzz66 You might need the full path to the binary, something like `/usr/bin/free` -- you can find the full path using e.g. `which` or `locate`.

**Comment by Andriuzz66** [comment]
@evert-mouw thanks for idea, but I used Wine program to ran bat file. Do I have to run bash file? casue I have renamed it to bat instead.

BR

**Comment by jwb6658** [comment]
I read using wine and I threw up in my mouth a little. Don’t do that. And if you don’t understand why that’s a bad thing, you should be paying someone like my company to configure your environment.

**Comment by evert-mouw** [comment]
Agreed with @jwb6658 and I'm done with lazy people who don't know even the basics. I'm closing this.
