### ISSUE TITLE
2nd NVidia GTX1060 6Gb is not being detected by Claymore Miner

### ISSUE THREAD

**Issue by triks786** [nanopool/Claymore-Dual-Miner#171]
Good Day all,

I have 2 Nvidia GTX 1060 6GB cards and a Gigabyte H110-D3A motherboard.
Both cards are correctly detected under Windows 10 device manager.
As soon as I excecute Claymore miner it detects GPU0 and GPU1.
It soon crash's and reports cannot get fan speed and temp. Claymore miner restarts automatically within the console and detects one GPU0 only. If anybody experienced similar issues please share your successful repairs.

Thank you.

Tahir Khan

**Comment by droneminer** [comment]
I have a similar problem. using asrock h110 pro btc+ mobo, two zotac 1060 6GB and one rx580 4GB everything works fine, BUT if i try replacing the rx 580 with another 1060, claymor crashes after a few seconds, and the third gpu starts spinning alarmingly fast. (corsair 750W)
I have updated driver and windows10, the risers are fine (work with other gpus) and the gpu also works if connect it separately.
Any ideas? could it be insufficient power?

**Comment by triks786** [comment]
Hi, 
I replaced the riser and seems to have resolved the issue.
