### ISSUE TITLE
Not able to control both Fan Speed

### ISSUE THREAD

**Issue by Nagendra080389** [nanopool/Claymore-Dual-Miner#185]
I am using this configuration :

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
EthDcrMiner64.exe -epool eth-asia1.nanopool.org:9999 -ewal ************************.Rx580_2/*****************@gmail.com -epsw x -mode 1 -ftime 10 -di 12 -tt 80 -fanmin 90

but somehow one gpu fan is controlled but the other is not controlled:
Please find the console output below:

E:\Etherum\Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v10.0>EthDcrMiner64.exe -epool eth-asia1.nanopool.org:9999 -ewal ************************.Rx580_2/*****************@gmail.com -epsw x -mode 1 -ftime 10 -di 12 -tt 80 -fanmin 90

╔════════════════════════════════════════════════════════════════╗
║     Claymore's Dual ETH + DCR/SC/LBC/PASC GPU Miner v10.0      ║
╚════════════════════════════════════════════════════════════════╝

ETH: 5 pools are specified
Main Ethereum pool is eth-asia1.nanopool.org:9999
At least 16 GB of Virtual Memory is required for multi-GPU systems
Make sure you defined GPU_MAX_ALLOC_PERCENT 100
Be careful with overclocking, use default clocks for first tests
Press "s" for current statistics, "0".."9" to turn on/off cards, "r" to reload pools, "e" or "d" to select current pool
OpenCL initializing...

AMD Cards available: 3
GPU #0: Ellesmere, 8192 MB available, 36 compute units
GPU #0 recognized as Radeon RX 480/580
GPU #1: Ellesmere, 8192 MB available, 36 compute units
GPU #1 recognized as Radeon RX 480/580
POOL/SOLO version
GPU #0: algorithm ASM
GPU #1: algorithm ASM
Total cards: 2
ETH: Stratum - connecting to 'eth-asia1.nanopool.org' <139.99.102.74> port 9999
ETH: Stratum - Connected (eth-asia1.nanopool.org:9999)
ETHEREUM-ONLY MINING MODE ENABLED (-mode 1)
ETH: eth-proxy stratum mode
Watchdog enabled
Remote management (READ-ONLY MODE) is enabled on port 3333

ETH: Authorized
Setting DAG epoch #163...
Setting DAG epoch #163 for GPU1
Setting DAG epoch #163 for GPU0
Create GPU buffer for GPU1
Create GPU buffer for GPU0
GPU0 DAG creation time - 6444 ms
Setting DAG epoch #163 for GPU0 done
GPU1 DAG creation time - 6462 ms
Setting DAG epoch #163 for GPU1 done
GPU0 t=58C fan=0%, GPU1 t=46C fan=89%

is there some more setting required to be done. The second GPU1 is showing 89% but the first one always shows 0% and moves up till 30%, but by that time the CPU0 temp is 72C approx, I would like to run the fan for both GPUs at 90 % so that the temp should not rise above 70C.

I want to do this from config because when the computer restarts after a power outage, I have my APM set to Switch ON the PC and have put the bat file to start the Claymore Miner in startup, hence I cannot use MSI afterburner to manually set the fans.

**Comment by Nagendra080389** [comment]
Its a setting in GPU that if the temp rises above some limit then only the fan works.
Closing the issue.

**Comment by ethical2012** [comment]
Ok. so you are the first link that comes up on google about this issue and you have basically told us nothing... 

Is it possible to do it through claymore... and how...
or is it ONLY through other software such as wattman, trixx, msi afterburner, what?

I wasnt trying to be rude but you just left us hanging....

**Comment by ethical2012** [comment]
also i forgot to add can this be fixed with gpu's on risers... etc...
