### ISSUE TITLE
Why does claymore show up as a virus in so many virus scans?

### ISSUE THREAD

**Issue by hibruh808** [nanopool/Claymore-Dual-Miner#202]
I just need to make sure that this program is safe. Do you think that you can explain why it shows up as this and what exactly it does to your computer.
Thanks,
Hibruh808

**Comment by jeremyisme** [comment]
https://bitcointalk.org/index.php?topic=1433925.0 Have a read here

**Comment by hibruh808** [comment]
It doesn't say why though

**Comment by jeremyisme** [comment]
"_Most of them are recognized as viruses by some paranoid antiviruses, perhaps because I pack my miners to protect them from disassembling, perhaps because some people include them into their botnets, or perhaps these antiviruses are not good, I don't know_"

**Comment by hibruh808** [comment]
Ok, ty den
