### ISSUE TITLE
Can't mine SiaCoin - Socket was closed remotely (by pool)

### ISSUE THREAD

**Issue by VictorEscalona** [nanopool/Claymore-Dual-Miner#21]
I have been trying to Dual Mine for the first time. I have been mining ETC and ETH only but now I want to dual mine. Unfortunately I am having issues with this, I have tried multiple things to try and fix it but been unsuccessful. Can anyone help me or is this a bug?

Batch file:

```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

EthDcrMiner64.exe -epool etc-eu1.nanopool.org:19999 -ewal MyWallet/MyWorker/MyEmail -epsw x -dpool stratum+tcp://sia-eu1.nanopool.org:7777 -dwal MyWallet/MyWorker/MyEmail -dpsw x -dcoin sia -ftime 10
```
Screenshot:
![1](https://user-images.githubusercontent.com/11059210/27333044-62128024-55bc-11e7-9e12-a0fd3dc1ce4c.PNG)

**Comment by carriere4** [comment]
try adding  "-mpool 0" to the end of your run command. this worked for me, but I decided not to dual-mine.

**Comment by ibell63** [comment]
It appears that you are attempting to mine on the ETC nanopool.  This miner is for ETH, not ETC.

**Comment by ibell63** [comment]
The only difference other than mining ETC instead of ETH appears to be that you've specified '-dpsw x' in your .bat file.  On Nanopool's example configuration, they don't have a password specified in the .bat, so maybe try removing that temporarily?

**Comment by VictorEscalona** [comment]
@carriere4 what is the -mpool flag for? It doesnt seem to be a flag for this miner.

@ibell63 I tried removing the -dpsw flag and no luck.

It appears that my issue is to do with the hashing, as you can see from the screenshot the GPU's are showing 0 Mh/s and maybe since it is not hashing anything the pool maybe closes the connection automatically. Anyone else have any other possible solutions? 😞

**Comment by BigslimVdub** [comment]
I am having this same issue. "Socket was closed remotely by pool (nanopool is what I'm using)"

Showing 000Mhs. Also is shows "DCR: Failed to get nonce1 at handshaking", DCR authorized is also prompted

**Comment by Reubenwelsh** [comment]
I had this issue and it turned out to be a firewall problem the port for outgoing traffic seemed to be flagged by my router, everything worked after turning the firewall in it off.

**Comment by BigslimVdub** [comment]
I had nothing but issues with nanopool and SIA. I ended up downloading marlin and mine straight SIA to SIAmining.com

**Comment by joshuaguild** [comment]
Some TP Link routers flag the incoming/outgoing requests as malware. I had to kill this and it was fine after that. Not sure why only dual mining is affected :/

**Comment by Agill-Sheron** [comment]
I have the same issue with one of my rigs. I disabled the firewall of the router and I still have the same problem. What is intriguing is that all my other rigs are connected to the same router and ... no problem. I tried different pools as well nut nothing. :/

**Comment by smussani** [comment]
@Agill-Sheron did you find a solution?  I have the same exact problem as yours..  Only one rig is giving me this error, the rest are working fine on the same router..  details below

I have been running 2 Ethereum rigs (6 GPU) on windows 10 for the past 3 weeks. Today all of a sudden I started getting Socket was closed remotely error from one of my rig.. 
everything works fine if I only have 1 GPU connected. But if I add more than one GPU, I get this error..

Asus Prime Z270 P motherboard 
Celeron Processor
4gb of RAM
Windows 10

I am using Claymore V10 and am only mining ETH. Both miner and windows recognize multiple GPUs


I even turned windows firewall off but it didn’t help

**Comment by Agill-Sheron** [comment]
@smussani I am certain that there is another way to solve this but I noticed that the wifi adapter I was using made a difference. I switched my wi-fi adapter to another one and everything worked fine. Try it and tell if it works out for you too.

**Comment by BigslimVdub** [comment]
If you are mining, you should not be using WiFi. You will have too high packer loss and the pool will temp ban your ip. If you can’t hard line the setups use a Powerline adaptor. https://www.bestbuy.com/site/netgear-powerline-network-adapter-white/4320444.p?skuId=4320444&cmp=RMX&extStoreId=14&ref=212&loc=1&ksid=2bfc6903-c82e-4aff-b749-9a078ca6c278&ksprof_id=3&ksaffcode=pg269160&ksdevice=m&lsft=ref:212,loc:2&gclid=CjwKCAiA15vTBRAHEiwA7SnfcwAgJnllN4zwPSLP41JrlVKzvj0w0sI80ZH0ZftFkyprfUsvxCfE9xoCbqsQAvD_BwE

**Comment by Agill-Sheron** [comment]
@BigslimVdub what's a packer loss? I am using wifi and it runs smoothly.

**Comment by BigslimVdub** [comment]
Sorry packet loss. When you use WiFi the connection isn’t that great and you will typically send bad shares or late shares to the pool that will get your miner (or sometimes ip) temporarily banned by the pool application. I noticed this specifically for nanopool SIA mining. I do not use WiFi but I did try once and it had way too many issues especially on 5ghz channels.

**Comment by Agill-Sheron** [comment]
I never got bad shares but I do get stale shares from time to time.

**Comment by smussani** [comment]
thanks @BigslimVdub.  Connecting directly using an LAN Ethernet cable solved my problem.  I didn't have an ethernet wall port, so I used a Powerline Ethernet Adapter
