### ISSUE TITLE
Claymore don’t reboot when a gpu get off

### ISSUE THREAD

**Issue by hamdyaea** [nanopool/Claymore-Dual-Miner#238]
Sometimes I have a gou who get off and I have to reboot windows manually. I am on win10 with the last version of claymore. I am dual mining eth + pasc. I have a reboot.bat who works fine usually but not always.

**Comment by hamdyaea** [comment]
02:12:19:024	184c	ETH - Total Speed: 45.380 Mh/s, Total Shares: 179, Rejected: 0, Time: 03:44
02:12:19:024	184c	ETH: GPU0 off, GPU1 24.917 Mh/s, GPU2 20.462 Mh/s

**Comment by dusopp** [comment]
I have almost the same problem. In my case reboot.bat is never called, when gpu hangs or all of them. Also -r 180 does not reload miner every 3hours.

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
EthDcrMiner64.exe -epool eth-eu1.nanopool.org:9999 -ewal 0xeb5f3067762b96ce1dd28a78d6f7f568ff67b15e.rig1/email@gmail.com -epsw x -mode 1 -ftime 10 -ethi 16 -gser 2 -wd 1 -r 180

**Comment by hamdyaea** [comment]
I have find the solution : I installed the last version of claymore (11.7) and Speedfan with an event for every gpu that say : if gpu 0 temperature < 50  execute reboot.bat
