### ISSUE TITLE
nVidia Ubunutu 16.04 - Perf Level switch 3 to 2 after start of miner

### ISSUE THREAD

**Issue by bjt02** [nanopool/Claymore-Dual-Miner#26]
My system is set for constant use of X Server Settings / PowerMizer / Perf level 3, once I start the miner it switches to 2. Any pointers?

./ethdcrminer64  -mode 0

Miner 9.5
GTX980ti
375.66 driver
Cuda v8
Ubuntu 16041

---

no Miner issue but expected behavior for such workloads and non games

**Comment by VogelxPsycho** [comment]
Did you manage to resolve this? I'm having the same problem.
