### ISSUE TITLE
How to disable the correct GPU

### ISSUE THREAD

**Issue by JackGzj** [nanopool/Claymore-Dual-Miner#282]
I run `nvidia-smi` order to check the GPU status, and the result shows that GPU0 and GPU3 has been using. I use the `-di 01 -di 03` order to disable these two GPUs, but I got error:`CUDA error - cannot allocate big buffer for DAG. Check readme.txt for possible solutions. GPU 0 failed`. I want to know how to set the `-di` order correctly.

**Comment by stone212** [comment]
@JackGzj DId you solve this problem?  If so can you post the solution?

**Comment by JackGzj** [comment]
> @JackGzj DId you solve this problem? If so can you post the solution?

In the past (I don't know which) version, I use -di detect -tt 80,80 to let claymore set the GPU order correctly as the GPU ID in nvidia-smi. But it seemed to be changed in the latest version.

**Comment by GeorgeHardyBTC** [comment]
@JackGzj Check this youtube video to help you to solve the problem:  https://www.youtube.com/watch?v=G1zTIfFC-hg
