### ISSUE TITLE
Error unzipping 9.3 release

### ISSUE THREAD

**Issue by nsutter** [nanopool/Claymore-Dual-Miner#3]
I have the error 0x80004005 when I try to unzip the release 9.3 on windows.

**Comment by fcjreed** [comment]
Your download probably became corrupt. Download to a flash drive from a different PC. I had no issues extracting on windows.

**Comment by nsutter** [comment]
Don't know what happened, I tried on several computers and download it several times but it didn't work. It's ok now :)
