### ISSUE TITLE
Windows 10 crashes with random colored screens RX 480

### ISSUE THREAD

**Issue by iamcubeman** [nanopool/Claymore-Dual-Miner#37]
Every time I run the miner (via NiceHash) after a few seconds, Windows 10 will crash with randomly colored screens and reboot. I've used the miner by itself and with Nicehash, and results are the same. As of this post, I'm using the latest driver version for my RX 480, and the latest updates for Windows 10 Pro.

**Comment by viktro78** [comment]
This appears to be a stability issue with your graphics card. That happens to me as well if I undervolt my card too far. Try bumping up the voltage if you're doing any overclocking/undervolting.

**Comment by iamcubeman** [comment]
My card is factory overclocked, but I have it underclocked to stock rx 480 with the card's default voltage. Do I doubt it's a clock speed issue. I did notice that when running super position benchmark in opengl mode, it'll crash the same way, but not in directX

**Comment by tcirre93** [comment]
I am also experiencing an issue with this in Windows 10. I am using a Sapphire Nitro+ 580 4gb gpu. All settings are stock. After a few minutes I experience crashes, colors. etc. This does not happen with other mining software

**Comment by Kiryu141** [comment]
If you are using the latest AMD drivers, I would recommend using the last drivers that were stable. Also, I avoid using my mining GPU as my display adapter to increase stability. If you have an option in BIOS to use onboard graphics, do that. Obviously make sure to connect to motherboard HDMI/DVI/VGA/DP

**Comment by iamcubeman** [comment]
My motherboard doesn't have onboard graphics, and gpu driver version doesn't seem to make a difference. I'll move this onto Nicehash Issues since that's the program I'm using, and seems to happen with all gpu miners.
