### ISSUE TITLE
Can not DUAL mine SIA

### ISSUE THREAD

**Issue by BigslimVdub** [nanopool/Claymore-Dual-Miner#47]
When I try to mine SIA dual (with nvidia) it prompts this:
DCR: Stratum - Connected (SIA-us-west1.nanopool.org:7777)
DCR: Failed to get nonce1 at handshake
DCR: Authorized

It will not connect to any SIA pool on nano pool.
No issues with ETH mining though.

**Comment by BigslimVdub** [comment]
Figured it out. 
You need these commands:

-mode 0
-esm 0
-asm 0

Hashing 28mh on 1070 ETH and 380mh SIA now

**Comment by bu5hm4nn** [comment]
@BigslimVdub Would you mind sharing your whole commandline?

**Comment by BigslimVdub** [comment]
EthDcrMiner64.exe -mode 0 -esm 0 -ethi 1 -epool us-west1.nanopool.org:9999 -ewal 0x88868686868686868686868686868686886.workername/email@gmail.com -epsw x -dcoin sia -dcri 100 -dpool stratum+tcp://sia-eu1.nanopool.org:7777 -dwal 99999999999999999999999999999999999999999999999/workername/email@gmail.com -dpsw x -tt 65 -ttli 76 -tstop 80 -asm 0


obviously add your own wallet.worker/email 

hashing 760 Mhs siacoin and 21.5Mh Eth with this setup on one 1070 8gb card pulling 245w at the wall also CPU mining with claymore cpu 280hs xmr

**Comment by lil-giygas** [comment]
@BigslimVdub Thank you!  This fixed my issue.
