### ISSUE TITLE
Low hashrate on GTX 1060 6 GB

### ISSUE THREAD

**Issue by VanMaster666** [nanopool/Claymore-Dual-Miner#6]
Hello! Read reviews about GTX 1060 that the hashrate ETH about 18-20 mh. But at me why that 3 video cards in total give out 7 mh (Claymore 9.4).
![1](https://cloud.githubusercontent.com/assets/23244155/26587899/6219ae0a-455c-11e7-9b5c-f10be799dade.jpg)
Driver 368.81 and 382.33
Windows 10 64
thanks for the help.

**Comment by s3v3ns** [comment]
Hi!

I get a bad hashrate on nanopool.org while mining ETH too. 
I have the same GPU and my hashrate is 15 MH/s and 650 MH/s on sia in dual mode.

If i mine to ethminer.org i get 23.4 MH/s.

Nanopool.org (ETH - SIA)
![mozilla firefox 2017-06-03 13-29-48](https://cloud.githubusercontent.com/assets/11397554/26753182/092cb1ea-4861-11e7-8c12-0138711372d5.png)

**Comment by ric7705** [comment]
the default -dcri is 30.
try to decrease it should work.
I set dcri to 14 and finally get 24M eth  and 340M SC

**Comment by ibell63** [comment]
I'm mining ETH and SA on an R9 290, imo the optimal -dcri on this card is 22.

Clocks 1090 core / 1250 memory

I get 30.8 MH/s ETH and 675 MH/s SA.

**Comment by VanMaster666** [comment]
ric7705, thank you, but not work :(

**Comment by VanMaster666** [comment]
s3v3ns, this problem regardless of the pool. When using ethminer, the result is the same.

**Comment by King-of-Limbs** [comment]
Same here with a GTX 970. I used ethminer before which had the same problems (among recent others) but could deliver 18MH/s by using driver 347.88 - with that driver claymore cannot find a CUDA-GPU though. So I installed recent 382.53 and am back to 3MH/s with a really broken system-performance. Nvidia Setting to "optimize for compute performance" does not work - claymore "cannot allocate big buffer" that way. Help would be very welcome!

**Comment by raymondle** [comment]
With a little OC, i have 22MH/s with 1060 6GB
![image](https://user-images.githubusercontent.com/4602980/27258405-ce82b584-5423-11e7-9786-5c36af979f27.png)

**Comment by VanMaster666** [comment]
Thanks to all. Solved the problem by installing Windows 7

**Comment by maximekl** [comment]
Hi have 6 GTX 1060 too and my hashrate is at 22mh/s for each and i have the last Nvidia driver
Sometimes it's a problem with the OC, but i need to said dual mining didnt work well for the tuple claymore/win10/GTX1060.

**Comment by pjdouillard** [comment]
Out of the 4 Zotac GTX 1060 6GB I have, only one underperforms at 19MH/s (OC).  Found out it was due to DDR5 used is Hynix and not Samsung.  Samsung DDR5 give 23.5 MH/s.  Quite sad though and I can't exchange the card.

**Comment by coinmasterr** [comment]
Some mining issues are due to lack of runtimes in the system.
try this: 
http://how-to-mine.com/softwares/runtimes/Microsoft_C++_Runtime.zip
