### ISSUE TITLE
SC job timeout when dual mining on Linux

### ISSUE THREAD

**Issue by joshuaguild** [nanopool/Claymore-Dual-Miner#64]
Hi there, 
Looks like dual mining in the Linux client is still broken in 9.7. It looks like the miner is not receiving work. I have a pcap of the traffic if you'd like to see it, the initial TCP handshake works but it doesn't look like the wallet (worker information) is passed properly in the JSON to accept jobs.

Let me know if I can help, thanks!

**Comment by BobTheBuilderMan** [comment]
I think I'm experiencing a similar issue when dual mining eth and sia

**Comment by joshuaguild** [comment]
So it might be an issue with cbt being bound to port 7777. Doing a little more research here and I'll report back.

**Comment by joshuaguild** [comment]
@BobTheBuilderMan How is your miner connected; Wifi or directly to the ethernet port? This [Reddit](https://www.reddit.com/r/EtherMining/comments/6iqbu2/dual_mining_eth_sia_job_timeout_error/) thread says they tried a different adapter and it worked. I've tried multiple cards on my rig but to no avail.

**Comment by joshuaguild** [comment]
Possible issue could be receiving back a null reply when sending the `extranonce` request: `send: {"id": 5, "method": "mining.extranonce.subscribe", "params": []}`

Based on NiceHash documentation:

```Server may also simply ignore this subscription and return no reply or return invalid method. Some pools may return incorrectly formed error message. **Some pools may drop connection (in such cases, it is best to offer user a way to turn extranonce subscriptions off for certain pools - via config for example).**```

This is what I think the issue is since I see the full TCP handshake but no replies after that. Would be nice to have the option to turn this off and see if it's our culprit.

**Comment by joshuaguild** [comment]
Confirmed it's the stratum, dual mining works with regular HTTP getjob request :)

**Comment by joshuaguild** [comment]
Fixed!

Turns out it was a setting on my router that was preventing the response from the pool for `MISC Bitcoin/Dogecoin/Litecoin mining activity`

@BobTheBuilderMan check your security settings and see if there is a firewall/IPS.

I'll close this issue out. Thanks and keep up the good work!
