### ISSUE TITLE
-ttli option has no effect

### ISSUE THREAD

**Issue by Roaders** [nanopool/Claymore-Dual-Miner#79]
Hi All

I am running with this command:

`EthDcrMiner64.exe -epool eu1.ethermine.org:4444 -ewal 0x06ac78d0bb2e6cc76990176ec29d17901fe7aa6c.Spa -epsw x -mode 1 -ftime 10 -ttli 85 -tstop 95`

but the -`ttli` option has no effect.

statistics output:

```
GPU #0: GeForce GTX 1080 Ti, 11264 MB available, 28 compute units, capability: 6.1

GPU #1: GeForce GTX 970, 4096 MB available, 13 compute units, capability: 5.2

ETH - Total Speed: 34.621 Mh/s, Total Shares: 3(3+0), Rejected: 0, Time: 00:06
ETH: GPU0 31.515 Mh/s, GPU1 3.106 Mh/s
Incorrect ETH shares: none
1 minute average ETH total speed: 34.493 Mh/s
Pool switches: ETH - 0, DCR - 0
Current ETH share target: 0x0000000112e0be82 (diff: 4000MH), epoch 138(2.08GB)
GPU0 t=92C fan=99%, GPU1 t=59C fan=59%
```

**Comment by veridicis** [comment]
Holy smokes, this is my 1080 Ti : 
ETH: GPU0 35.507 Mh/s
GPU0 t=82C fan=76%

Overclocked with MSI Afterburner, Win7 x64

**Comment by Roaders** [comment]
well, my 970 is installed right next to the 1080...

not ideal but that's the only way it would fit in the case.

I am thinking of removing it.

**Comment by veridicis** [comment]
Are you using the 1080Ti FE?

**Comment by Roaders** [comment]
I don't know what that is so probably not!

**Comment by veridicis** [comment]
GTX 1080 Ti Founders Edition, it has bad cooling.

**Comment by Roaders** [comment]
Nope, I have 
Palit Geforce GTX 1080 Ti JetStream 11GB GDDR5X Graphics Card

**Comment by veridicis** [comment]
Ok!
From Readme file:
-ttli	reduce entire mining intensity (for all coins) automatically if GPU temperature is above specified value. For example, "-ttli 80" reduces mining intensity if GPU temperature is above 80C.
	You can see if intensity was reduced in detailed statistics ("s" key).
	You can also specify values for every card, for example "-ttli 80,85,80". You also should specify non-zero value for "-tt" option to enable this option.
	It is a good idea to set "-ttli" value higher than "-tt" value by 3-5C.

I see you don't use the "-tt" option :)

**Comment by Roaders** [comment]
hmmmm.... I didn't set that as it said that it's not supported on nvidia cards...
I'll give it a go. Thanks

**Comment by veridicis** [comment]
Ah yes! Sorry, did not read that part. I do the temperature management via Afterburner

**Comment by Roaders** [comment]
nope, still doesn't seem to work with this:

`EthDcrMiner64.exe -epool eu1.ethermine.org:4444 -ewal 0x06ac78d0bb2e6cc76990176ec29d17901fe7aa6c.Spa -epsw x -mode 1 -ftime 10 -tt 85 -ttli 90 -tstop 100`

**Comment by Roaders** [comment]
this is a duplicate of #75
