### ISSUE TITLE
Only 1 GTX 970 card out of 2 found

### ISSUE THREAD

**Issue by Roaders** [nanopool/Claymore-Dual-Miner#83]
Hi

I have just setup a brand new clean install PC with windows 7 and 2 Nvidia GTX 970 cards.

When running Claymore it only sees 1 of the cards.

Any suggestions on how to get it to find and use the second card?

Thanks

**Comment by imjunez** [comment]
Does the windows detect your 2nd GPU? On NVIDIA Control Panel or Device Manager.

**Comment by Roaders** [comment]
No, windows didn't see the second card. It turns out that the PCIe slot I was using doesn't seem to work.

I moved the card to another slot (that makes cooling both cards difficult) and now both are seen and used.

Thanks
