### ISSUE TITLE
Random switches between DAG 

### ISSUE THREAD

**Issue by entity279** [nanopool/Claymore-Dual-Miner#92]
Cannot possibly fathom why this happens :

![clipboard01](https://user-images.githubusercontent.com/18208760/29577182-3b6c3a4e-8773-11e7-880a-384a81c989d6.jpg)

**Comment by GabrielNotman** [comment]
I also encountered this issue using 9.8 on Ubuntu 16.04.
I was also using eu1.ethermine.org and seeing switches between 139 and 128.

**Comment by entity279** [comment]
I've tried ethminer and it was working fine.. but now claymore also works. So it is the pool's fault, it would seem ?

**Comment by GabrielNotman** [comment]
Yeah it could quite possibly be an issue with that specific pool.

I checked check my logs, it first showed up today at about 11:30 BST.

The numerous switches caused my miner to crash.

I've switched back to 9.7 for now as I have had to unrecoverable crashes in the last 3 days.

**Comment by webbertakken** [comment]
Having the same issue on both rigs with completely different hardware. Coincidentally with eu1.ethermine.org as well. 

Can any confirm this for any other pool or their us links, or prove a negative with eu1.ethermine.org?
