### ISSUE TITLE
Claymore Remote 

### ISSUE THREAD

**Issue by spot88** [nanopool/Claymore-Dual-Miner#97]
Hello! Do this only support remote on LAN, not WAN?

**Comment by spot88** [comment]
Anyone know?

**Comment by joshuaguild** [comment]
You can open it up to a WAN by port forwarding on your router.

**Comment by rontran** [comment]
Open up the port (default 3333) on your firewall.

**Comment by spot88** [comment]
Okay, so it is possible.

**Comment by spot88** [comment]
Thanks!

**Comment by rontran** [comment]
That is how tcp/ip works.
